CREATE USER ${POSTGRES_DJANGO_USER} WITH PASSWORD ${POSTGRES_DJANGO_PASSWORD};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_DJANGO_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_DJANGO_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_DJANGO_USER};
GRANT SELECT ON spatial_ref_sys TO ${POSTGRES_DJANGO_USER};


CREATE USER ${POSTGRES_QGIS_USER} WITH PASSWORD ${POSTGRES_QGIS_PASSWORD};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO POSTGRES_QGIS_USER;
GRANT USAGE ON SCHEMA public TO POSTGRES_QGIS_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO POSTGRES_QGIS_USER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO POSTGRES_QGIS_USER;
GRANT SELECT ON spatial_ref_sys TO POSTGRES_QGIS_USER;


CREATE USER ${POSTGRES_BOT_USER} WITH LOGIN PASSWORD ${POSTGRES_BOT_PASSWORD};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_BOT_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_BOT_USER};

GRANT SELECT, INSERT ON spatial_features TO ${POSTGRES_BOT_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_BOT_USER};
GRANT SELECT ON spatial_ref_sys TO ${POSTGRES_BOT_USER};


ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_DJANGO_USER};
